### ISSUE TITLE
使用示例中的英文医疗数据运行一次的大体时间是多少

### ISSUE THREAD

**Issue by RainyNian** [willing510/MindMap#13]
如题

**Comment by wyl-willing** [comment]
英文的知识图谱构建几分钟左右，中文的比较大，需要几十分钟

霖念 ***@***.***>于2024年6月14日 周五15:33写道：

**Comment by wyl-willing** [comment]
构建了一次以后，第二次就可以注销构建知识图谱步骤直接进行推理了。

Yilin Wen ***@***.***>于2024年6月15日 周六10:02写道：

**Comment by RainyNian** [comment]
感谢
