### ISSUE TITLE
很多关键文件都缺失了

### ISSUE THREAD

**Issue by adgjlzcama** [willing510/MindMap#18]
大佬，好多文件都不在啊，比如`pre-training\chatdoctor5k\encode_keyword_entity.py` 里面提到的 `dataset3_ner.json` , 还有 `pre-training\cmcqa\MindMap_CMCQA.py` 里面的`./data/cmcqa/entity_embeddings.pkl` 和 `./data/cmcqa/keyword_embeddings.pkl` 这些文件都没有

**Comment by wyl-willing** [comment]
在readme里面我备注了，这个文件太大我上传到谷歌硬盘了

adgjlzcama ***@***.***>于2024年8月17日 周六15:47写道：

**Comment by adgjlzcama** [comment]
感谢回复! 但是翻遍了google文件无法找到为 cmcqa 提供的 `encode_keyword_entity.py` (只有chatdoctor5k的`encode_keyword_entity.py` ), 请问是否可以公开这个文件？

**Comment by wyl-willing** [comment]
你好，在data的cmcqa的readme的谷歌链接里面。

adgjlzcama ***@***.***>于2024年8月17日 周六17:33写道：

**Comment by adgjlzcama** [comment]
谢谢，我翻的就是这个[google链接](https://drive.google.com/drive/folders/1Q1ac87vJ59mgM9fz4KI20xyAyUOvxU0W )，但是里面只有最终的`encode_keyword_entity.pkl`文件，而不是用来生成的这个`.pkl`的`encode_keyword_entity.py`文件

**Comment by wyl-willing** [comment]
pre-training/chatdoctor5k/encode_keyword_entity.py

中文的和英文是一样的方法，我没有存下来，麻烦参考一下数据一中的。

adgjlzcama ***@***.***>于2024年8月17日 周六17:48写道：
