### ISSUE TITLE
代码好像没把Mindmap的输出结果写进output.csv

### ISSUE THREAD

**Issue by adgjlzcama** [willing510/MindMap#19]
在MindMap.py 中，原本output.csv 的第三列好像是计划写入MindMap的回答，但是在代码末尾，第三列好像被写入了Chatgpt3.5的回答。
https://github.com/wyl-willing/MindMap/blob/0411a54719e9b90176d02e937ab73d2df5e25963/MindMap.py#L421-L423

https://github.com/wyl-willing/MindMap/blob/0411a54719e9b90176d02e937ab73d2df5e25963/MindMap.py#L785-L788

**Comment by wyl-willing** [comment]
代码里面output_all是mindmap的回答。谢谢指出，我应该是分批次存储的。结果文件中有一列明显的有mindmap格式的答案。

adgjlzcama ***@***.***>于2024年8月22日 周四10:12写道：
