### ISSUE TITLE
代码没有写明MindMap用的是GPT3.5还是4

### ISSUE THREAD

**Issue by adgjlzcama** [willing510/MindMap#20]
我在论文的abstract中读到MindMap好像是基于gpt3.5, 但是MindMap的主程序运行过程中调用的都是chat，而不是chat_35 或 chat_4, 所以无法确认MindMap的整个运行过程中都需要哪些版本的LLM
https://github.com/wyl-willing/MindMap/blob/0411a54719e9b90176d02e937ab73d2df5e25963/MindMap.py#L220

**Comment by wyl-willing** [comment]
采用的是langchain的gpt对应版本 ，现在langchain更新了，可以运行openai 0.28.1，langchain 0.0.330


adgjlzcama ***@***.***>于2024年8月24日 周六20:54写道：

**Comment by adgjlzcama** [comment]
感谢回复，想确认一下，MindMap这里没有指明用的具体是哪个gpt，但是默认的话就是3.5吧
https://github.com/wyl-willing/MindMap/blob/0411a54719e9b90176d02e937ab73d2df5e25963/MindMap.py#L415

**Comment by wyl-willing** [comment]
实验的时候有写哦，所有baseline还有mindmap都是gpt3.5，除了gpt4

adgjlzcama ***@***.***>于2024年8月24日 周六21:17写道：
