### ISSUE TITLE
 the key of "question_kg"  is must be set or not?

### ISSUE THREAD

**Issue by evanlin88** [willing510/MindMap#8]
in the file of Chinese_doctor_qa_ner.json , the key of "question_kg"  is must be set some value before run MindMap_CMCQA.py?

**Comment by wyl-willing** [comment]
这一步我们是采用gpt生成的，也可以用个小模型或者任意其他方法替代。得到关键词以后，再与知识图谱中的实体匹配。

evanlin88 ***@***.***>于2024年6月7日 周五09:57写道：
